stages:
  - deploy

prod:
  stage: deploy
  image: php:7.2
  only:
    - master

  script:
    - ./.gitlab-deploy-prod
    - scp -P 2121 -rv php/web cgu@cgurtner.ch:tmp/test.cgurtner.ch
    - ssh -p2121 cgu@cgurtner.ch 'rm -rfv httpdocs/subdomain/test.cgurtner.ch && mv -v tmp/test.cgurtner.ch httpdocs/subdomain/test.cgurtner.ch'

  before_script:
    - apt-get update && apt-get install -y git zip unzip
    - cd /tmp

    # install composer
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - ln -s /tmp/composer.phar /bin/composer

    # install sass
    - curl -L https://github.com/sass/dart-sass/releases/download/1.14.1/dart-sass-1.14.1-linux-x64.tar.gz --output sass.tar.gz
    - tar xvf sass.tar.gz
    - rm -f sass.tar.gz
    - ln -s /tmp/dart-sass/sass /bin/sass

    - cd /builds/cgurtner.ch/CGU/php/web
    - composer install
    - sass gui/scss:gui/css
    - cd /builds/cgurtner.ch/CGU/

    # install openssh-client
    # create .ssh directory
    # add SSH_PRIVATE_KEY and SSH_KNOWN_HOSTS from gitlab.com variable
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts